# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache:
  directories:
  - $HOME/.local/share/renv
  - $TRAVIS_BUILD_DIR/renv/library

before_install:
  - Rscript -e "install.packages('renv')"

install:
  - Rscript -e "renv::restore()"

script:
  - Rscript -e '1 + 1'
