# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r_binary_packages: renv
cache:
  directories:
  - $HOME/.local/share/renv
  - $TRAVIS_BUILD_DIR/renv/library

install:
  - Rscript -e "renv::restore()"

script:
  - Rscript -e '1 + 1'
